-- Generated by wallust; consumed by mini.base16 in init.lua.
return {
  base00 = "{{background}}", base01 = "{{color0}}", base02 = "{{color0}}", base03 = "{{color8}}",
  base04 = "{{color7}}", base05 = "{{foreground}}", base06 = "{{color15}}", base07 = "{{color15}}",
  base08 = "{{color1}}", base09 = "{{color9}}", base0A = "{{color3}}", base0B = "{{color2}}",
  base0C = "{{color6}}", base0D = "{{color4}}", base0E = "{{color5}}", base0F = "{{color13}}",
}
